spring.application.name=payflow-backend
server.port=8080

# JWT Configuration
jwt.secret=8NqLk3R7pV9xY2mH6dT4wF1zC5aJ8sQ0XnB2eU7iK9oL4rM6pV3yT8wE1qZ5uC2
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000